### ISSUE TITLE
PIO analysis for unrestricted system

### ISSUE THREAD

**Issue by usedgo** [jxzhangcc/PIO#2]
I want to know if this PIO analysis can only be used for restricted system?  I tried several times for an unrestricted molecule, but failed.

**Comment by jxzhangcc** [comment]
Sorry to reply very late. Actually we have been working on it in the recent months and the new version will be available online in days.

**Comment by jxzhangcc** [comment]
> I want to know if this PIO analysis can only be used for restricted system? I tried several times for an unrestricted molecule, but failed.
Sorry to reply very late. Actually we have been working on it in the recent months and the new version will be available online in days.

**Comment by jxzhangcc** [comment]
> I want to know if this PIO analysis can only be used for restricted system? I tried several times for an unrestricted molecule, but failed.

Sorry to reply very late. Actually we have been working on it in the recent months and the new version will be available online in days.

**Comment by usedgo** [comment]
thanks!

**Comment by usedgo** [comment]
> > I want to know if this PIO analysis can only be used for restricted system? I tried several times for an unrestricted molecule, but failed.
> 
> Sorry to reply very late. Actually we have been working on it in the recent months and the new version will be available online in days.

thanks!
